macro(force_include_header target)
    foreach(header IN LISTS ARGN)
        if(MSVC)
            target_compile_options(${target} PRIVATE /FI"${header}")
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            target_compile_options(${target} PRIVATE -include "${header}")
        else()
            message(WARNING "Unknown compiler for force include: ${CMAKE_CXX_COMPILER_ID}")
        endif()
    endforeach()
endmacro(force_include_header)
