name: Build

on: push

env:
  BUILD_TYPE: Release

jobs:
  build: 
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        config:
          - os: windows-2022
            extra_cmake: ' -A "x64"'
            compiler: "cl"

          - os: ubuntu-22.04
            extra_cmake: ""
            compiler: "g++-12"

          - os: ubuntu-22.04
            extra_cmake: ""
            compiler: "clang++-15"


    runs-on: ${{matrix.config.os}}
    name: ${{ matrix.config.os }} - ${{ matrix.config.compiler }} - ${{ matrix.build_type }}

    steps:
      - name: Set up Clang
        if: runner.os == "Linux" && ${{ matrix.config.compiler }} == "clang++-15"
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15

      - uses: actions/checkout@v3.1.0
      - name: Configure CMake
        run: cmake -Bbuild-D CMAKE_CXX_COMPILER=${{ matrix.config.compiler }} ${{ matrix.config.extra_cmake }} ..

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}
