name: Build

on: push

env:
  BUILD_TYPE: Release

jobs:
  build: 
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        config:
          - os: windows-2022
            extra_cmake: ' -A "x64"'
            compiler: "cl"

          - os: ubuntu-22.04
            extra_cmake: ""
            compiler: "g++-12"

# TODO: reenable this when clang 15 is available
          # - os: ubuntu-22.04
          #   extra_cmake: ""
          #   compiler: "clang++-15"


    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} - ${{ matrix.config.compiler }} - ${{ matrix.build_type }}

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Create build directory
        shell: bash
        run: mkdir -p ${{ github.workspace }}/${{ matrix.config.working_directory }}

      - name: Configure CMake
        shell: bash
        run: cmake -Bbuild -D CMAKE_CXX_COMPILER=${{ matrix.config.compiler }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE ${{ matrix.config.extra_cmake }} $GITHUB_WORKSPACE

      - name: Build
        shell: bash
        run: cmake --build build --config ${{ matrix.build_type }}
