name: CMake

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        compiler:
          - cc: gcc-10
            cxx: g++-10
          - cc: clang
            cxx: clang++
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print compiler version
        run: $CC -v && $CXX -v

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build lib
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Configure and build examples
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_EXAMPLE=ON
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
