name: CMake

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        cxx_compiler: [g++-10, clang++-11, clang++-12]

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake
              -B ${{github.workspace}}/build
              -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}}
              -DBUILD_EXAMPLE=ON

      - name: Build lib
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}